
import { Word, Category, Language } from './types';

export const CATEGORIES: Category[] = ['Noun', 'Verb', 'Adjective', 'Adverb'];

export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' }
];

export const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome stalker!",
    subWelcome: "Choose your languages and start hunting.",
    sourceLabel: "My native language",
    targetLabel: "Target language",
    startBtn: "Start hunting 🏹",
    statsTitle: "Stalker stats",
    level: "Level",
    points: "Puan",
    score: "Puan",
    target: "Target language",
    map: "Map",
    levelSelectTitle: "Galaxy map",
    levelSelectSub: "Planet locked. Initiate descent?",
    analyzing: "Scanning galaxy...",
    stalkerMode: "Advanced stalker",
    textMode: "Text mode",
    visualPattern: "Analyze signal",
    progress: "Progress",
    promoted: "Mission successful!",
    levelClear: "Planet clear",
    nextSector: "Next planet 🚀",
    locked: "+10",
    compromised: "-5",
    training: "Training",
    fieldWork: "Field work",
    backToSetup: "Back to languages",
    nextLevel: "Next level",
    failed: "Mission failed",
    failedSub: "You must get at least 40/50 to advance.",
    retry: "Retry level 🔄"
  },
  tr: {
    welcome: "Hoşgeldin takipçi!",
    subWelcome: "Dillerini seç ve avlanmaya başla.",
    sourceLabel: "Ana dilim",
    targetLabel: "Hedef dil",
    startBtn: "Avlanmaya başla 🏹",
    statsTitle: "Takipçi istatistikleri",
    level: "Seviye",
    points: "Puan",
    score: "Puan",
    target: "Hedef dil",
    map: "Harita",
    levelSelectTitle: "Galaksi haritası",
    levelSelectSub: "Gezegen kilitlendi. İniş yapılsın mı?",
    analyzing: "Galaksi taranıyor...",
    stalkerMode: "Gelişmiş takipçi",
    textMode: "Metin modu",
    visualPattern: "Sinyali analiz et",
    progress: "İlerleme",
    promoted: "İz sürme başarıyla tamamlandı",
    levelClear: "Gezegen tamamlandı",
    nextSector: "Sıradaki seviye 🚀",
    locked: "+10",
    compromised: "-5",
    training: "Eğitim",
    fieldWork: "Saha görevi",
    backToSetup: "Dillere dön",
    nextLevel: "Sıradaki seviye",
    failed: "Görev başarısız",
    failedSub: "İlerlemek için en az 40/50 yapmalısın.",
    retry: "Seviyeyi tekrarla 🔄"
  },
  fr: {
    welcome: "Bienvenue traqueur !",
    subWelcome: "Choisissez vos langues et commencez la chasse.",
    sourceLabel: "Ma langue maternelle",
    targetLabel: "Langue cible",
    startBtn: "Commencer la chasse 🏹",
    statsTitle: "Stats du traqueur",
    level: "Niveau",
    points: "Puan",
    score: "Puan",
    target: "Langue cible",
    map: "Carte",
    levelSelectTitle: "Carte galactique",
    levelSelectSub: "Planète verrouillée. Lancer la descente ?",
    analyzing: "Analyse de la galaxie...",
    stalkerMode: "Traqueur avancé",
    textMode: "Mode texte",
    visualPattern: "Analyser le signal",
    progress: "Progression",
    promoted: "Mission réussie !",
    levelClear: "Planète terminée",
    nextSector: "Planète suivante 🚀",
    locked: "+10",
    compromised: "-5",
    training: "Entraînement",
    fieldWork: "Sur le terrain",
    backToSetup: "Retour aux langues",
    nextLevel: "Niveau suivant",
    failed: "Mission échouée",
    failedSub: "Vous devez obtenir au moins 40/50 pour avancer.",
    retry: "Réessayer le niveau 🔄"
  }
};

const createLevel = (level: number, words: [string, string, string, Category][]): Word[] => {
  return words.map((w, i) => ({
    id: `l${level}-${i}`,
    en: w[0],
    fr: w[1],
    tr: w[2],
    category: w[3],
    rarity: level
  }));
};

export const WORD_DATABASE: Word[] = [
  // SEVİYE 1-2: FİİLLER (Verbs - 50 each)
  ...createLevel(1, [
    ['Go', 'Aller', 'Gitmek', 'Verb'], ['Come', 'Venir', 'Gelmek', 'Verb'], ['Do', 'Faire', 'Yapmak', 'Verb'],
    ['Say', 'Dire', 'Söylemek', 'Verb'], ['Give', 'Donner', 'Vermek', 'Verb'], ['Take', 'Prendre', 'Almak', 'Verb'],
    ['Eat', 'Manger', 'Yemek', 'Verb'], ['Drink', 'Boire', 'İçmek', 'Verb'], ['Run', 'Courir', 'Koşmak', 'Verb'],
    ['Walk', 'Marcher', 'Yürümek', 'Verb'], ['Jump', 'Sauter', 'Zıplamak', 'Verb'], ['Sleep', 'Dormir', 'Uyumak', 'Verb'],
    ['Work', 'Travailler', 'Çalışmak', 'Verb'], ['Play', 'Jouer', 'Oynamak', 'Verb'], ['Read', 'Lire', 'Okumak', 'Verb'],
    ['Write', 'Écrire', 'Yazmak', 'Verb'], ['Listen', 'Écouter', 'Dinlemek', 'Verb'], ['See', 'Voir', 'Görmek', 'Verb'],
    ['Hear', 'Entendre', 'Duymak', 'Verb'], ['Know', 'Savoir', 'Bilmek', 'Verb'], ['Think', 'Penser', 'Düşünmek', 'Verb'],
    ['Buy', 'Acheter', 'Satın almak', 'Verb'], ['Sell', 'Vendre', 'Satmak', 'Verb'], ['Find', 'Trouver', 'Bulmak', 'Verb'],
    ['Lose', 'Perdre', 'Kaybetmek', 'Verb'], ['Make', 'Fabriquer', 'Üretmek', 'Verb'], ['Build', 'Construire', 'İnşa etmek', 'Verb'],
    ['Choose', 'Choisir', 'Seçmek', 'Verb'], ['Call', 'Appeler', 'Aramak', 'Verb'], ['Clean', 'Nettoyer', 'Temizlemek', 'Verb'],
    ['Drive', 'Conduire', 'Sürmek', 'Verb'], ['Cook', 'Cuisiner', 'Pişirmek', 'Verb'], ['Bake', 'Cuire au four', 'Fırınlamak', 'Verb'],
    ['Cut', 'Couper', 'Kesmek', 'Verb'], ['Draw', 'Dessiner', 'Çizmek', 'Verb'], ['Dream', 'Rêver', 'Rüya görmek', 'Verb'],
    ['Dress', 'S\'habiller', 'Giyinmek', 'Verb'], ['Fall', 'Tomber', 'Düşmek', 'Verb'], ['Feel', 'Sentir', 'Hissetmek', 'Verb'],
    ['Fight', 'Se battre', 'Dövüşmek', 'Verb'], ['Fly', 'Voler', 'Uçmak', 'Verb'], ['Grow', 'Grandir', 'Büyümek', 'Verb'],
    ['Hold', 'Tenir', 'Tutmak', 'Verb'], ['Keep', 'Garder', 'Tutmak', 'Verb'], ['Laugh', 'Rire', 'Gülmek', 'Verb'],
    ['Learn', 'Apprendre', 'Öğrenmek', 'Verb'], ['Leave', 'Partir', 'Ayrılmak', 'Verb'], ['Look', 'Regarder', 'Bakmak', 'Verb'],
    ['Love', 'Aimer', 'Sevmek', 'Verb'], ['Move', 'Bouger', 'Hareket etmek', 'Verb']
  ]),
  ...createLevel(2, [
    ['Begin', 'Commencer', 'Başlamak', 'Verb'], ['Finish', 'Finir', 'Bitirmek', 'Verb'], ['Open', 'Ouvrir', 'Açmak', 'Verb'],
    ['Close', 'Fermer', 'Kapatmak', 'Verb'], ['Stop', 'Arrêter', 'Durdurmak', 'Verb'], ['Start', 'Démarrer', 'Başlatmak', 'Verb'],
    ['Wait', 'Attendre', 'Beklemek', 'Verb'], ['Ask', 'Demander', 'Sormak', 'Verb'], ['Answer', 'Répondre', 'Cevaplamak', 'Verb'],
    ['Help', 'Aider', 'Yardım etmek', 'Verb'], ['Understand', 'Comprendre', 'Anlamak', 'Verb'], ['Remember', 'Se souvenir', 'Hatırlamak', 'Verb'],
    ['Forget', 'Oublier', 'Unutmak', 'Verb'], ['Wash', 'Laver', 'Yıkamak', 'Verb'], ['Fix', 'Réparer', 'Tamir etmek', 'Verb'],
    ['Bring', 'Apporter', 'Getirmek', 'Verb'], ['Send', 'Envoyer', 'Göndermek', 'Verb'], ['Change', 'Changer', 'Değiştirmek', 'Verb'],
    ['Open', 'Ouvrir', 'Açmak', 'Verb'], ['Close', 'Fermer', 'Kapatmak', 'Verb'], ['Smile', 'Sourire', 'Gülümsemek', 'Verb'],
    ['Touch', 'Toucher', 'Dokunmak', 'Verb'], ['Taste', 'Goûter', 'Tadına bakmak', 'Verb'], ['Smell', 'Sentir', 'Koklamak', 'Verb'],
    ['Listen', 'Écouter', 'Dinlemek', 'Verb'], ['Watch', 'Regarder', 'İzlemek', 'Verb'], ['Push', 'Pousser', 'İtmek', 'Verb'],
    ['Pull', 'Tirer', 'Çekmek', 'Verb'], ['Sing', 'Chanter', 'Şarkı söylemek', 'Verb'], ['Dance', 'Danser', 'Dans etmek', 'Verb'],
    ['Swim', 'Nager', 'Yüzmek', 'Verb'], ['Climb', 'Grimper', 'Tırmanmak', 'Verb'], ['Travel', 'Voyager', 'Seyahat etmek', 'Verb'],
    ['Visit', 'Visiter', 'Ziyaret etmek', 'Verb'], ['Stay', 'Rester', 'Kalmak', 'Verb'], ['Sleep', 'Dormir', 'Uyumak', 'Verb'],
    ['Wake', 'Se réveiller', 'Uyanmak', 'Verb'], ['Sit', 'S\'asseoir', 'Oturmak', 'Verb'], ['Stand', 'Se tenir debout', 'Ayakta durmak', 'Verb'],
    ['Believe', 'Croire', 'İnanmak', 'Verb'], ['Hope', 'Espérer', 'Ummak', 'Verb'], ['Try', 'Essayer', 'Denemek', 'Verb'],
    ['Win', 'Gagner', 'Kazanmak', 'Verb'], ['Live', 'Vivre', 'Yaşamak', 'Verb'], ['Die', 'Mourir', 'Ölmek', 'Verb'],
    ['Show', 'Montrer', 'Göstermek', 'Verb'], ['Hide', 'Cacher', 'Gizlemek', 'Verb'], ['Teach', 'Enseigner', 'Öğretmek', 'Verb'],
    ['Practice', 'Pratiquer', 'Pratik yapmak', 'Verb'], ['Solve', 'Résoudre', 'Çözmek', 'Verb']
  ]),

  // SEVİYE 3-4: EV (Home - 50 each)
  ...createLevel(3, [
    ['House', 'Maison', 'Ev', 'Noun'], ['Room', 'Chambre', 'Oda', 'Noun'], ['Kitchen', 'Cuisine', 'Mutfak', 'Noun'],
    ['Bed', 'Lit', 'Yatak', 'Noun'], ['Chair', 'Chaise', 'Sandalye', 'Noun'], ['Table', 'Table', 'Masa', 'Noun'],
    ['Door', 'Porte', 'Kapı', 'Noun'], ['Window', 'Fenêtre', 'Pencere', 'Noun'], ['Wall', 'Mur', 'Duvar', 'Noun'],
    ['Floor', 'Sol', 'Zemin', 'Noun'], ['Ceiling', 'Plafond', 'Tavan', 'Noun'], ['Key', 'Clé', 'Anahtar', 'Noun'],
    ['Lock', 'Serrure', 'Kilit', 'Noun'], ['Mirror', 'Miroir', 'Ayna', 'Noun'], ['Curtain', 'Rideau', 'Perde', 'Noun'],
    ['Lamp', 'Lampe', 'Lamba', 'Noun'], ['Shelf', 'Étagère', 'Raf', 'Noun'], ['Drawer', 'Tiroir', 'Çekmece', 'Noun'],
    ['Pillow', 'Oreiller', 'Yastık', 'Noun'], ['Blanket', 'Couverture', 'Battaniye', 'Noun'], ['Wardrobe', 'Armoire', 'Gardırop', 'Noun'],
    ['Bathroom', 'Salle de bain', 'Banyo', 'Noun'], ['Toilet', 'Toilettes', 'Tuvalet', 'Noun'], ['Shower', 'Douche', 'Duş', 'Noun'],
    ['Soap', 'Savon', 'Sabun', 'Noun'], ['Carpet', 'Tapis', 'Halı', 'Noun'], ['Roof', 'Toit', 'Çatı', 'Noun'],
    ['Chimney', 'Cheminée', 'Baca', 'Noun'], ['Stairs', 'Escaliers', 'Merdivenler', 'Noun'], ['Balcony', 'Balcon', 'Balkon', 'Noun'],
    ['Garden', 'Jardin', 'Bahçe', 'Noun'], ['Fence', 'Clôture', 'Çit', 'Noun'], ['Gate', 'Porte', 'Kapı', 'Noun'],
    ['Vase', 'Vase', 'Vazo', 'Noun'], ['Painting', 'Tableau', 'Tablo', 'Noun'], ['Clock', 'Horloge', 'Saat', 'Noun'],
    ['Fan', 'Ventilateur', 'Vantilatör', 'Noun'], ['Radiator', 'Radiateur', 'Radyatör', 'Noun'], ['Plug', 'Prise', 'Fiş', 'Noun'],
    ['Light', 'Lumière', 'Işık', 'Noun'], ['Couch', 'Canapé', 'Kanepe', 'Noun'], ['Armchair', 'Fauteuil', 'Tekli koltuk', 'Noun'],
    ['Desks', 'Bureaux', 'Masalar', 'Noun'], ['Sofa', 'Sofa', 'Koltuk', 'Noun'], ['Cushion', 'Coussin', 'Minder', 'Noun'],
    ['Ashtray', 'Cendrier', 'Küllük', 'Noun'], ['Trash can', 'Poubelle', 'Çöp kutusu', 'Noun'], ['Hallway', 'Couloir', 'Koridor', 'Noun'],
    ['Basement', 'Sous-sol', 'Bodrum', 'Noun'], ['Attic', 'Grenier', 'Tavan arası', 'Noun']
  ]),
  ...createLevel(4, [
    ['Plate', 'Assiette', 'Tabak', 'Noun'], ['Bowl', 'Bol', 'Kase', 'Noun'], ['Cup', 'Tasse', 'Fincan', 'Noun'],
    ['Glass', 'Verre', 'Bardak', 'Noun'], ['Fork', 'Fourchette', 'Çatal', 'Noun'], ['Knife', 'Couteau', 'Bıçak', 'Noun'],
    ['Spoon', 'Cuillère', 'Kaşık', 'Noun'], ['Pot', 'Marmite', 'Tencere', 'Noun'], ['Pan', 'Poêle', 'Tava', 'Noun'],
    ['Fridge', 'Frigo', 'Buzdolabı', 'Noun'], ['Oven', 'Four', 'Fırın', 'Noun'], ['Stove', 'Cuisinière', 'Ocak', 'Noun'],
    ['Sink', 'Évier', 'Lavabo', 'Noun'], ['Towel', 'Serviette', 'Havlu', 'Noun'], ['Brush', 'Brosse', 'Fırça', 'Noun'],
    ['Comb', 'Peigne', 'Tarak', 'Noun'], ['Shampoo', 'Shampooing', 'Şampuan', 'Noun'], ['Hammer', 'Marteau', 'Çekiç', 'Noun'],
    ['Screwdriver', 'Tournevis', 'Tornavida', 'Noun'], ['Ladder', 'Échelle', 'Merdiven', 'Noun'], ['Garden', 'Jardin', 'Bahçe', 'Noun'],
    ['Toaster', 'Grille-pain', 'Ekmek kızartma makinesi', 'Noun'], ['Microwave', 'Micro-ondes', 'Mikrodalga', 'Noun'], ['Blender', 'Mélangeur', 'Blender', 'Noun'],
    ['Kettle', 'Bouilloire', 'Su ısıtıcısı', 'Noun'], ['Teapot', 'Théière', 'Çaydanlık', 'Noun'], ['Tray', 'Plateau', 'Tepsi', 'Noun'],
    ['Napkin', 'Serviette', 'Peçete', 'Noun'], ['Jug', 'Carafe', 'Sürahi', 'Noun'], ['Broom', 'Balai', 'Süpürge', 'Noun'],
    ['Mop', 'Serpillière', 'Vileda', 'Noun'], ['Iron', 'Fer à repasser', 'Ütü', 'Noun'], ['Dishwasher', 'Lave-vaisselle', 'Bulaşık makinesi', 'Noun'],
    ['Washer', 'Lave-linge', 'Çamaşır makinesi', 'Noun'], ['Dryer', 'Sèche-linge', 'Kurutma makinesi', 'Noun'], ['Vacuum', 'Aspirateur', 'Elektrik süpürgesi', 'Noun'],
    ['Bucket', 'Seau', 'Kova', 'Noun'], ['Hose', 'Tuyau', 'Hortum', 'Noun'], ['Tools', 'Outils', 'Aletler', 'Noun'],
    ['Screw', 'Vis', 'Vida', 'Noun'], ['Nail', 'Clou', 'Çivi', 'Noun'], ['Saw', 'Scie', 'Testere', 'Noun'],
    ['Drill', 'Perceuse', 'Matkap', 'Noun'], ['Gloves', 'Gants', 'Eldivenler', 'Noun'], ['Candle', 'Bougie', 'Mum', 'Noun'],
    ['Match', 'Allumette', 'Kibrit', 'Noun'], ['Flashlight', 'Lampe de poche', 'El feneri', 'Noun'], ['Battery', 'Pile', 'Pil', 'Noun'],
    ['Tape', 'Ruban adhésif', 'Bant', 'Noun'], ['Glue', 'Colle', 'Yapıştırıcı', 'Noun']
  ]),

  // SEVİYE 5-6: OKUL (School - 50 each)
  ...createLevel(5, [
    ['School', 'École', 'Okul', 'Noun'], ['Teacher', 'Professeur', 'Öğretmen', 'Noun'], ['Student', 'Étudiant', 'Öğrenci', 'Noun'],
    ['Classroom', 'Salle de classe', 'Sınıf', 'Noun'], ['Desk', 'Bureau', 'Sıra', 'Noun'], ['Book', 'Livre', 'Kitap', 'Noun'],
    ['Notebook', 'Cahier', 'Defter', 'Noun'], ['Pen', 'Stylo', 'Kalem', 'Noun'], ['Pencil', 'Crayon', 'Kurşun kalem', 'Noun'],
    ['Eraser', 'Gomme', 'Silgi', 'Noun'], ['Ruler', 'Règle', 'Cetvel', 'Noun'], ['Backpack', 'Sac à dos', 'Sırt çantası', 'Noun'],
    ['Paper', 'Papier', 'Kağıt', 'Noun'], ['Board', 'Tableau', 'Tahta', 'Noun'], ['Marker', 'Feutre', 'Marker', 'Noun'],
    ['Exam', 'Examen', 'Sınav', 'Noun'], ['Grade', 'Note', 'Not', 'Noun'], ['Lesson', 'Leçon', 'Ders', 'Noun'],
    ['Homework', 'Devoirs', 'Ödev', 'Noun'], ['Library', 'Bibliothèque', 'Kütüphane', 'Noun'], ['Subject', 'Sujet', 'Konu', 'Noun'],
    ['Dictionary', 'Dictionnaire', 'Sözlük', 'Noun'], ['Map', 'Carte', 'Harita', 'Noun'], ['Glue', 'Colle', 'Yapıştırıcı', 'Noun'],
    ['Scissors', 'Ciseaux', 'Makas', 'Noun'], ['Sharpener', 'Taille-crayon', 'Kalemtraş', 'Noun'], ['Stapler', 'Agrafeuse', 'Zımba', 'Noun'],
    ['Clip', 'Trombone', 'Ataç', 'Noun'], ['Folder', 'Dossier', 'Dosya', 'Noun'], ['Calculator', 'Calculatrice', 'Hesap makinesi', 'Noun'],
    ['Compass', 'Compas', 'Pergel', 'Noun'], ['Globe', 'Globe', 'Küre', 'Noun'], ['Poster', 'Affiche', 'Poster', 'Noun'],
    ['Locker', 'Casier', 'Dolap', 'Noun'], ['Bell', 'Cloche', 'Zil', 'Noun'], ['Principal', 'Directeur', 'Müdür', 'Noun'],
    ['Coach', 'Entraîneur', 'Antrenör', 'Noun'], ['Campus', 'Campus', 'Kampüs', 'Noun'], ['Hallway', 'Couloir', 'Koridor', 'Noun'],
    ['Laboratory', 'Laboratoire', 'Laboratuvar', 'Noun'], ['Science', 'Science', 'Fen', 'Noun'], ['Break', 'Pause', 'Mola', 'Noun'],
    ['Projector', 'Projecteur', 'Projeksiyon', 'Noun'], ['Notebook', 'Cahier', 'Defter', 'Noun'], ['Paint', 'Peinture', 'Boya', 'Noun'],
    ['Crayons', 'Crayons de couleur', 'Pastel boyalar', 'Noun'], ['Chalk', 'Craie', 'Tebeşir', 'Noun'], ['Diploma', 'Diplôme', 'Diploma', 'Noun'],
    ['Scholarship', 'Bourse', 'Burs', 'Noun'], ['Attendance', 'Présence', 'Yoklama', 'Noun']
  ]),
  ...createLevel(6, [
    ['History', 'Histoire', 'Tarih', 'Noun'], ['Geography', 'Géographie', 'Coğrafya', 'Noun'], ['Science', 'Science', 'Fen', 'Noun'],
    ['Math', 'Mathématiques', 'Matematik', 'Noun'], ['Art', 'Art', 'Resim', 'Noun'], ['Music', 'Musique', 'Müzik', 'Noun'],
    ['Sport', 'Sport', 'Spor', 'Noun'], ['Biology', 'Biologie', 'Biyoloji', 'Noun'], ['Chemistry', 'Chimie', 'Kimya', 'Noun'],
    ['Physics', 'Physique', 'Fizik', 'Noun'], ['Literature', 'Littérature', 'Edebiyat', 'Noun'], ['Grammar', 'Grammaire', 'Dilbilgisi', 'Noun'],
    ['Philosophy', 'Philosophie', 'Felsefe', 'Noun'], ['Economics', 'Économie', 'Ekonomi', 'Noun'], ['Lecture', 'Conférence', 'Konferans', 'Noun'],
    ['Seminar', 'Séminaire', 'Seminer', 'Noun'], ['Exercise', 'Exercice', 'Alıştırma', 'Noun'], ['Question', 'Question', 'Soru', 'Noun'],
    ['Answer', 'Réponse', 'Cevap', 'Noun'], ['Test', 'Test', 'Test', 'Noun'], ['Review', 'Révision', 'Tekrar', 'Noun'],
    ['Knowledge', 'Connaissance', 'Bilgi', 'Noun'], ['Discovery', 'Découverte', 'Keşif', 'Noun'], ['Study', 'Étude', 'Çalışma', 'Noun'],
    ['Research', 'Recherche', 'Araştırma', 'Noun'], ['Thesis', 'Thèse', 'Tez', 'Noun'], ['Semester', 'Semestre', 'Dönem', 'Noun'],
    ['Schedule', 'Emploi du temps', 'Program', 'Noun'], ['Meeting', 'Réunion', 'Toplantı', 'Noun'], ['Activity', 'Activité', 'Etkinlik', 'Noun'],
    ['Club', 'Club', 'Kulüp', 'Noun'], ['Team', 'Équipe', 'Takım', 'Noun'], ['Event', 'Événement', 'Etkinlik', 'Noun'],
    ['Competition', 'Compétition', 'Yarışma', 'Noun'], ['Medal', 'Médaille', 'Madalya', 'Noun'], ['Prize', 'Prix', 'Ödül', 'Noun'],
    ['Ceremony', 'Cérémonie', 'Tören', 'Noun'], ['Uniform', 'Uniforme', 'Üniforma', 'Noun'], ['Bag', 'Sac', 'Çanta', 'Noun'],
    ['Holiday', 'Vacances', 'Tatil', 'Noun'], ['Success', 'Succès', 'Başarı', 'Noun'], ['Fail', 'Échec', 'Başarısızlık', 'Noun'],
    ['Rules', 'Règles', 'Kurallar', 'Noun'], ['Classmate', 'Camarade de classe', 'Sınıf arkadaşı', 'Noun'], ['Reading', 'Lecture', 'Okuma', 'Noun'],
    ['Writing', 'Écriture', 'Yazma', 'Noun'], ['Speaking', 'Parole', 'Konuşma', 'Noun'], ['Listening', 'Écoute', 'Dinleme', 'Noun'],
    ['Translation', 'Traduction', 'Çeviri', 'Noun'], ['Vocabulary', 'Vocabulaire', 'Kelime hazinesi', 'Noun']
  ]),

  // SEVİYE 7-8: ALIŞVERİŞ & HAVALİMANI (50 each)
  ...createLevel(7, [
    ['Market', 'Marché', 'Market', 'Noun'], ['Price', 'Prix', 'Fiyat', 'Noun'], ['Money', 'Argent', 'Para', 'Noun'],
    ['Cash', 'Espèces', 'Nakit', 'Noun'], ['Card', 'Carte', 'Kart', 'Noun'], ['Bag', 'Sac', 'Çanta', 'Noun'],
    ['Bread', 'Pain', 'Ekmek', 'Noun'], ['Milk', 'Lait', 'Süt', 'Noun'], ['Egg', 'Œuf', 'Yumurta', 'Noun'],
    ['Cheese', 'Fromage', 'Peynir', 'Noun'], ['Meat', 'Viande', 'Et', 'Noun'], ['Chicken', 'Poulet', 'Tavuk', 'Noun'],
    ['Butcher', 'Boucher', 'Kasap', 'Noun'], ['Fish', 'Poisson', 'Balık', 'Noun'], ['Sugar', 'Sucre', 'Şeker', 'Noun'],
    ['Salt', 'Sel', 'Tuz', 'Noun'], ['Water', 'Eau', 'Su', 'Noun'], ['Juice', 'Jus', 'Meyve suyu', 'Noun'],
    ['Buy', 'Acheter', 'Satın almak', 'Verb'], ['Sell', 'Vendre', 'Satmak', 'Verb'], ['Cheap', 'Bon marché', 'Ucuz', 'Adjective'],
    ['Expensive', 'Cher', 'Pahalı', 'Adjective'], ['Discount', 'Remise', 'İndirim', 'Noun'], ['Receipt', 'Reçu', 'Fiş', 'Noun'],
    ['Customer', 'Client', 'Müşteri', 'Noun'], ['Shop', 'Magasin', 'Dükkan', 'Noun'], ['Store', 'Boutique', 'Mağaza', 'Noun'],
    ['Grocery', 'Épicerie', 'Bakkal', 'Noun'], ['Shelf', 'Étagère', 'Raf', 'Noun'], ['Aisle', 'Allée', 'Reyon', 'Noun'],
    ['Cart', 'Chariot', 'Sepet', 'Noun'], ['Basket', 'Panier', 'Sepet', 'Noun'], ['Counter', 'Comptoir', 'Tezgah', 'Noun'],
    ['Queue', 'File d\'attente', 'Sıra', 'Noun'], ['Worker', 'Travailleur', 'Çalışan', 'Noun'], ['Change', 'Monnaie', 'Para üstü', 'Noun'],
    ['Coin', 'Pièce', 'Madeni para', 'Noun'], ['Bill', 'Billet', 'Banknot', 'Noun'], ['Wallet', 'Portefeuille', 'Cüzdan', 'Noun'],
    ['Price tag', 'Étiquette de prix', 'Fiyat etiketi', 'Noun'], ['Total', 'Total', 'Toplam', 'Noun'], ['Pay', 'Payer', 'Ödemek', 'Verb'],
    ['Scan', 'Scanner', 'Tarama', 'Verb'], ['Delivery', 'Livraison', 'Teslimat', 'Noun'], ['Offer', 'Offre', 'Teklif', 'Noun'],
    ['Box', 'Boîte', 'Kutu', 'Noun'], ['Packet', 'Paquet', 'Paket', 'Noun'], ['Bottle', 'Bouteille', 'Şişe', 'Noun'],
    ['Can', 'Canette', 'Teneke kutu', 'Noun'], ['Bag', 'Sac', 'Çanta', 'Noun']
  ]),
  ...createLevel(8, [
    ['Airport', 'Aéroport', 'Havalimanı', 'Noun'], ['Plane', 'Avion', 'Uçak', 'Noun'], ['Ticket', 'Billet', 'Bilet', 'Noun'],
    ['Passport', 'Passeport', 'Pasaport', 'Noun'], ['Luggage', 'Bagage', 'Bagaj', 'Noun'], ['Suitcase', 'Valise', 'Valiz', 'Noun'],
    ['Check-in', 'Enregistrement', 'Kayıt', 'Noun'], ['Flight', 'Vol', 'Uçuş', 'Noun'], ['Pilot', 'Pilote', 'Pilot', 'Noun'],
    ['Gate', 'Porte', 'Kapı', 'Noun'], ['Seat', 'Siège', 'Koltuk', 'Noun'], ['Arrival', 'Arrivée', 'Varış', 'Noun'],
    ['Departure', 'Départ', 'Kalkış', 'Noun'], ['Delay', 'Retard', 'Gecikme', 'Noun'], ['Belt', 'Ceinture', 'Kemer', 'Noun'],
    ['Window', 'Fenêtre', 'Pencere', 'Noun'], ['Exit', 'Sortie', 'Çıkış', 'Noun'], ['Control', 'Contrôle', 'Kontrol', 'Noun'],
    ['Customs', 'Douane', 'Gümrük', 'Noun'], ['Passenger', 'Passager', 'Yolcu', 'Noun'], ['Security', 'Sécurité', 'Güvenlik', 'Noun'],
    ['Duty-free', 'Hors taxes', 'Gümrüksüz', 'Adjective'], ['Terminal', 'Terminal', 'Terminal', 'Noun'], ['Lounge', 'Salon', 'Bekleme salonu', 'Noun'],
    ['Runway', 'Piste', 'Pist', 'Noun'], ['Take-off', 'Décollage', 'Kalkış', 'Noun'], ['Landing', 'Atterrissage', 'İniş', 'Noun'],
    ['Visa', 'Visa', 'Vize', 'Noun'], ['Stamp', 'Timbre', 'Mühür', 'Noun'], ['Baggage claim', 'Récupération des bagages', 'Bagaj alımı', 'Noun'],
    ['Boarding pass', 'Carte d\'embarquement', 'Biniş kartı', 'Noun'], ['Coach', 'Économique', 'Ekonomi sınıfı', 'Noun'], ['First class', 'Première classe', 'Birinci sınıf', 'Noun'],
    ['Cabin', 'Cabine', 'Kabin', 'Noun'], ['Crew', 'Équipage', 'Mürettebat', 'Noun'], ['Stewardess', 'Hôtesse de l\'air', 'Hostes', 'Noun'],
    ['Travel', 'Voyage', 'Seyahat', 'Noun'], ['Flight number', 'Numéro de vol', 'Uçuş numarası', 'Noun'], ['Delay', 'Retard', 'Gecikme', 'Noun'],
    ['Cancel', 'Annuler', 'İptal etmek', 'Verb'], ['Book', 'Réserver', 'Rezervasyon yapmak', 'Verb'], ['Announcement', 'Annonce', 'Duyuru', 'Noun'],
    ['Sky', 'Ciel', 'Gökyüzü', 'Noun'], ['Clouds', 'Nuages', 'Bulutlar', 'Noun'], ['Ocean', 'Océan', 'Okyanus', 'Noun'],
    ['Destination', 'Destination', 'Varış noktası', 'Noun'], ['Map', 'Carte', 'Harita', 'Noun'], ['Souvenir', 'Souvenir', 'Hediyelik eşya', 'Noun'],
    ['Tourist', 'Touriste', 'Turist', 'Noun'], ['Information', 'Information', 'Bilgi', 'Noun']
  ]),

  // SEVİYE 9-10: ULAŞIM & ELEKTRONİK (50 each)
  ...createLevel(9, [
    ['Car', 'Voiture', 'Araba', 'Noun'], ['Bus', 'Bus', 'Otobüs', 'Noun'], ['Truck', 'Camion', 'Kamyon', 'Noun'],
    ['Train', 'Train', 'Tren', 'Noun'], ['Bike', 'Vélo', 'Bisiklet', 'Noun'], ['Motorcycle', 'Moto', 'Motosiklet', 'Noun'],
    ['Boat', 'Bateau', 'Tekne', 'Noun'], ['Ship', 'Navire', 'Gemi', 'Noun'], ['Wheel', 'Roue', 'Tekerlek', 'Noun'],
    ['Engine', 'Moteur', 'Motor', 'Noun'], ['Brake', 'Frein', 'Fren', 'Noun'], ['Road', 'Route', 'Yol', 'Noun'],
    ['Street', 'Rue', 'Sokak', 'Noun'], ['Traffic', 'Trafik', 'Trafik', 'Noun'], ['Light', 'Feu', 'Işık', 'Noun'],
    ['Sign', 'Signe', 'Tabela', 'Noun'], ['Bridge', 'Pont', 'Köprü', 'Noun'], ['Tunnel', 'Tunnel', 'Tünel', 'Noun'],
    ['Garage', 'Garage', 'Garaj', 'Noun'], ['Parking', 'Parking', 'Otopark', 'Noun'], ['Driver', 'Chauffeur', 'Sürücü', 'Noun'],
    ['Passenger', 'Passager', 'Yolcu', 'Noun'], ['Gas', 'Essence', 'Benzin', 'Noun'], ['Station', 'Station', 'İstasyon', 'Noun'],
    ['Highway', 'Autoroute', 'Otoyol', 'Noun'], ['Subway', 'Métro', 'Metro', 'Noun'], ['Tram', 'Tramway', 'Tramvay', 'Noun'],
    ['Helicopter', 'Hélicoptère', 'Helikopter', 'Noun'], ['Bicycle', 'Bicyclette', 'Bisiklet', 'Noun'], ['Scooter', 'Scooter', 'Skuter', 'Noun'],
    ['Ambulance', 'Ambulance', 'Ambulans', 'Noun'], ['Taxi', 'Taxi', 'Taksi', 'Noun'], ['Route', 'Route', 'Rota', 'Noun'],
    ['Map', 'Carte', 'Harita', 'Noun'], ['Speed', 'Vitesse', 'Hız', 'Noun'], ['Accident', 'Accident', 'Kaza', 'Noun'],
    ['Danger', 'Danger', 'Tehlike', 'Noun'], ['Warning', 'Avertissement', 'Uyarı', 'Noun'], ['Lane', 'Voie', 'Şerit', 'Noun'],
    ['Intersection', 'Intersection', 'Kavşak', 'Noun'], ['Crosswalk', 'Passage piétons', 'Yaya geçidi', 'Noun'], ['Sidewalk', 'Trottoir', 'Kaldırım', 'Noun'],
    ['Pavement', 'Chaussée', 'Asfalt', 'Noun'], ['Ticket', 'Billet', 'Bilet', 'Noun'], ['Fair', 'Tarif', 'Ücret', 'Noun'],
    ['Arrival', 'Arrivée', 'Varış', 'Noun'], ['Departure', 'Départ', 'Kalkış', 'Noun'], ['Wait', 'Attendre', 'Beklemek', 'Verb'],
    ['Go', 'Aller', 'Gitmek', 'Verb'], ['Stop', 'Arrêter', 'Durmak', 'Verb']
  ]),
  ...createLevel(10, [
    ['Phone', 'Téléphone', 'Telefon', 'Noun'], ['Computer', 'Ordinateur', 'Bilgisayar', 'Noun'], ['Laptop', 'Portable', 'Dizüstü', 'Noun'],
    ['Screen', 'Écran', 'Ekran', 'Noun'], ['Keyboard', 'Clavier', 'Klavye', 'Noun'], ['Mouse', 'Souris', 'Fare', 'Noun'],
    ['Battery', 'Batterie', 'Batarya', 'Noun'], ['Charger', 'Chargeur', 'Şarj aleti', 'Noun'], ['Internet', 'Internet', 'İnternet', 'Noun'],
    ['Website', 'Site web', 'Web sitesi', 'Noun'], ['Email', 'E-mail', 'E-posta', 'Noun'], ['Password', 'Mot de passe', 'Şifre', 'Noun'],
    ['App', 'Application', 'Uygulama', 'Noun'], ['Message', 'Message', 'Mesaj', 'Noun'], ['Camera', 'Appareil photo', 'Kamera', 'Noun'],
    ['Television', 'Télévision', 'Televizyon', 'Noun'], ['Radio', 'Radio', 'Radyo', 'Noun'], ['Speaker', 'Haut-parleur', 'Hoparlör', 'Noun'],
    ['Headphones', 'Casque', 'Kulaklık', 'Noun'], ['Tablet', 'Tablette', 'Tablet', 'Noun'], ['Printer', 'Imprimante', 'Yazıcı', 'Noun'],
    ['Monitor', 'Moniteur', 'Monitör', 'Noun'], ['Software', 'Logiciel', 'Yazılım', 'Noun'], ['Hardware', 'Matériel', 'Donanım', 'Noun'],
    ['Memory', 'Mémoire', 'Hafıza', 'Noun'], ['Cloud', 'Cloud', 'Bulut', 'Noun'], ['Network', 'Réseau', 'Ağ', 'Noun'],
    ['Signal', 'Signal', 'Sinyal', 'Noun'], ['Wifi', 'Wifi', 'Wifi', 'Noun'], ['Bluetooth', 'Bluetooth', 'Bluetooth', 'Noun'],
    ['Volume', 'Volume', 'Ses', 'Noun'], ['Bright', 'Luminosité', 'Parlaklık', 'Noun'], ['Display', 'Affichage', 'Görüntü', 'Noun'],
    ['Settings', 'Paramètres', 'Ayarlar', 'Noun'], ['Update', 'Mise à jour', 'Güncelleme', 'Noun'], ['Download', 'Téléchargement', 'İndirme', 'Noun'],
    ['Upload', 'Chargement', 'Yükleme', 'Noun'], ['File', 'Fichier', 'Dosya', 'Noun'], ['Folder', 'Dossier', 'Klasör', 'Noun'],
    ['Icon', 'Icône', 'Simge', 'Noun'], ['Link', 'Lien', 'Bağlantı', 'Noun'], ['User', 'Utilisateur', 'Kullanıcı', 'Noun'],
    ['Account', 'Compte', 'Hesap', 'Noun'], ['Login', 'Connexion', 'Giriş', 'Noun'], ['Logout', 'Déconnexion', 'Çıkış', 'Noun'],
    ['Code', 'Code', 'Kod', 'Noun'], ['Error', 'Erreur', 'Hata', 'Noun'], ['Fix', 'Réparer', 'Tamir', 'Noun'],
    ['Develop', 'Développer', 'Geliştirmek', 'Verb'], ['Program', 'Programmer', 'Programlamak', 'Verb']
  ]),

  // SEVİYE 11-12: SEBZE, MEYVE & YEMEK (50 each)
  ...createLevel(11, [
    ['Apple', 'Pomme', 'Elma', 'Noun'], ['Banana', 'Banane', 'Muz', 'Noun'], ['Orange', 'Orange', 'Portakal', 'Noun'],
    ['Strawberry', 'Fraise', 'Çilek', 'Noun'], ['Grape', 'Raisin', 'Üzüm', 'Noun'], ['Lemon', 'Citron', 'Limon', 'Noun'],
    ['Watermelon', 'Pastèque', 'Karpuz', 'Noun'], ['Peach', 'Pêche', 'Şeftali', 'Noun'], ['Cherry', 'Cerise', 'Kiraz', 'Noun'],
    ['Melon', 'Melon', 'Kavun', 'Noun'], ['Pineapple', 'Ananas', 'Ananas', 'Noun'], ['Mango', 'Mangue', 'Mango', 'Noun'],
    ['Kiwi', 'Kiwi', 'Kivi', 'Noun'], ['Plum', 'Prune', 'Erik', 'Noun'], ['Apricot', 'Abricot', 'Kayısı', 'Noun'],
    ['Pear', 'Poire', 'Armut', 'Noun'], ['Pomegranate', 'Grenade', 'Nar', 'Noun'], ['Fig', 'Figue', 'İncir', 'Noun'],
    ['Tomato', 'Tomate', 'Domates', 'Noun'], ['Potato', 'Pomme de terre', 'Patates', 'Noun'], ['Carrot', 'Carotte', 'Havuç', 'Noun'],
    ['Onion', 'Oignon', 'Soğan', 'Noun'], ['Garlic', 'Ail', 'Sarımsak', 'Noun'], ['Cucumber', 'Concombre', 'Salatalık', 'Noun'],
    ['Pepper', 'Poivre', 'Biber', 'Noun'], ['Corn', 'Maïs', 'Mısır', 'Noun'], ['Mushroom', 'Champignon', 'Mantar', 'Noun'],
    ['Lettuce', 'Laitue', 'Marul', 'Noun'], ['Olive', 'Olive', 'Zeytin', 'Noun'], ['Spinach', 'Épinards', 'Ispanak', 'Noun'],
    ['Broccoli', 'Brocoli', 'Brokoli', 'Noun'], ['Cabbage', 'Chou', 'Lahana', 'Noun'], ['Peas', 'Petis pois', 'Bezelye', 'Noun'],
    ['Beans', 'Haricots', 'Fasulye', 'Noun'], ['Eggplant', 'Aubergine', 'Patlıcan', 'Noun'], ['Zucchini', 'Courgette', 'Kabak', 'Noun'],
    ['Radish', 'Radis', 'Turp', 'Noun'], ['Celery', 'Céleri', 'Kereviz', 'Noun'], ['Parsley', 'Persil', 'Maydanoz', 'Noun'],
    ['Basil', 'Basilic', 'Fesleğen', 'Noun'], ['Mint', 'Menthe', 'Nane', 'Noun'], ['Ginger', 'Gingembre', 'Zencefil', 'Noun'],
    ['Pumpkin', 'Citrouille', 'Kabak', 'Noun'], ['Cauliflower', 'Chou-fleur', 'Karnabahar', 'Noun'], ['Asparagus', 'Asperge', 'Kuşkonmaz', 'Noun'],
    ['Artichoke', 'Artichaut', 'Enginar', 'Noun'], ['Nut', 'Noix', 'Ceviz', 'Noun'], ['Almond', 'Amande', 'Badem', 'Noun'],
    ['Hazelnut', 'Noisette', 'Fındık', 'Noun'], ['Peanut', 'Cacahuète', 'Yer fıstığı', 'Noun']
  ]),
  ...createLevel(12, [
    ['Meal', 'Repas', 'Öğün', 'Noun'], ['Breakfast', 'Petit déjeuner', 'Kahvaltı', 'Noun'], ['Lunch', 'Déjeuner', 'Öğle yemeği', 'Noun'],
    ['Dinner', 'Dîner', 'Akşam yemeği', 'Noun'], ['Soup', 'Soupe', 'Çorba', 'Noun'], ['Salad', 'Salade', 'Salata', 'Noun'],
    ['Rice', 'Riz', 'Pirinç', 'Noun'], ['Pasta', 'Pâtes', 'Makarna', 'Noun'], ['Pizza', 'Pizza', 'Pizza', 'Noun'],
    ['Burger', 'Burger', 'Burger', 'Noun'], ['Sandwich', 'Sandwich', 'Sandviç', 'Noun'], ['Cake', 'Gâteau', 'Pasta', 'Noun'],
    ['Cookie', 'Biscuit', 'Kurabiye', 'Noun'], ['Ice cream', 'Glace', 'Dondurma', 'Noun'], ['Chocolate', 'Chocolat', 'Çikolata', 'Noun'],
    ['Tea', 'Thé', 'Çay', 'Noun'], ['Coffee', 'Café', 'Kahve', 'Noun'], ['Honey', 'Miel', 'Bal', 'Noun'],
    ['Butter', 'Beurre', 'Tereyağı', 'Noun'], ['Oil', 'Huile', 'Yağ', 'Noun'], ['Yogurt', 'Yaourt', 'Yoğurt', 'Noun'],
    ['Cream', 'Crème', 'Krema', 'Noun'], ['Jam', 'Confiture', 'Reçel', 'Noun'], ['Egg', 'Œuf', 'Yumurta', 'Noun'],
    ['Meat', 'Viande', 'Et', 'Noun'], ['Steak', 'Steak', 'Biftek', 'Noun'], ['Kebab', 'Kebab', 'Kebap', 'Noun'],
    ['Fish', 'Poisson', 'Balık', 'Noun'], ['Shrimp', 'Crevette', 'Karides', 'Noun'], ['Sausage', 'Saucisse', 'Sosis', 'Noun'],
    ['Ham', 'Jambon', 'Jambon', 'Noun'], ['Bacon', 'Bacon', 'Pastırma', 'Noun'], ['Cheese', 'Fromage', 'Peynir', 'Noun'],
    ['Bread', 'Pain', 'Ekmek', 'Noun'], ['Toast', 'Toast', 'Tost', 'Noun'], ['Omelet', 'Omelette', 'Omlet', 'Noun'],
    ['Soup', 'Soupe', 'Çorba', 'Noun'], ['Stew', 'Ragoût', 'Yahnı', 'Noun'], ['Sauce', 'Sauce', 'Sos', 'Noun'],
    ['Vinegar', 'Vinaigre', 'Sirke', 'Noun'], ['Spices', 'Épices', 'Baharatlar', 'Noun'], ['Pepper', 'Poivre', 'Karabiber', 'Noun'],
    ['Salt', 'Sel', 'Tuz', 'Noun'], ['Sugar', 'Sucre', 'Şeker', 'Noun'], ['Candy', 'Bonbon', 'Şekerleme', 'Noun'],
    ['Pie', 'Tarte', 'Turta', 'Noun'], ['Pastry', 'Pâtisserie', 'Hamur işi', 'Noun'], ['Donut', 'Donut', 'Donut', 'Noun'],
    ['Menu', 'Menu', 'Menü', 'Noun'], ['Bill', 'Addition', 'Hesap', 'Noun']
  ]),

  // SEVİYE 13-14: SANAT, MESLEK & AKSESUAR (50 each)
  ...createLevel(13, [
    ['Painting', 'Peinture', 'Resim', 'Noun'], ['Sculpture', 'Sculpture', 'Heykel', 'Noun'], ['Music', 'Musique', 'Müzik', 'Noun'],
    ['Dance', 'Danse', 'Dans', 'Noun'], ['Theatre', 'Théâtre', 'Tiyatro', 'Noun'], ['Cinema', 'Cinéma', 'Sinema', 'Noun'],
    ['Artist', 'Artiste', 'Sanatçı', 'Noun'], ['Writer', 'Écrivain', 'Yazar', 'Noun'], ['Singer', 'Chanteur', 'Şarkıcı', 'Noun'],
    ['Actor', 'Aktör', 'Aktör', 'Noun'], ['Guitar', 'Guitare', 'Gitar', 'Noun'], ['Piano', 'Piano', 'Piyano', 'Noun'],
    ['Violin', 'Violon', 'Keman', 'Noun'], ['Frame', 'Cadre', 'Çerçeve', 'Noun'], ['Color', 'Couleur', 'Renk', 'Noun'],
    ['Brush', 'Pinceau', 'Fırça', 'Noun'], ['Canvas', 'Toile', 'Tuval', 'Noun'], ['Art', 'Art', 'Sanat', 'Noun'],
    ['Drawing', 'Dessin', 'Çizim', 'Noun'], ['Design', 'Design', 'Tasarım', 'Noun'], ['Poem', 'Poème', 'Şiir', 'Noun'],
    ['Novel', 'Roman', 'Roman', 'Noun'], ['Scene', 'Scène', 'Sahne', 'Noun'], ['Play', 'Pièce', 'Oyun', 'Noun'],
    ['Musical', 'Comédie musicale', 'Müzikal', 'Noun'], ['Band', 'Groupe', 'Grup', 'Noun'], ['Stage', 'Scène', 'Sahne', 'Noun'],
    ['Audience', 'Public', 'Seyirci', 'Noun'], ['Performance', 'Performance', 'Performans', 'Noun'], ['Creative', 'Créatif', 'Yaratıcı', 'Adjective'],
    ['Masterpiece', 'Chef-d\'œuvre', 'Başyapıt', 'Noun'], ['Gallery', 'Galerie', 'Galeri', 'Noun'], ['Museum', 'Musée', 'Müze', 'Noun'],
    ['Exhibit', 'Exposition', 'Sergi', 'Noun'], ['Abstract', 'Abstrait', 'Soyut', 'Adjective'], ['Modern', 'Moderne', 'Modern', 'Adjective'],
    ['Classic', 'Classique', 'Klasik', 'Adjective'], ['Style', 'Style', 'Tarz', 'Noun'], ['Pattern', 'Motif', 'Desen', 'Noun'],
    ['Sketch', 'Croquis', 'Taslak', 'Noun'], ['Illustration', 'Illustration', 'İllüstrasyon', 'Noun'], ['Craft', 'Artisanat', 'Zanaat', 'Noun'],
    ['Photography', 'Photographie', 'Fotoğrafçılık', 'Noun'], ['Camera', 'Caméra', 'Kamera', 'Noun'], ['Director', 'Directeur', 'Yönetmen', 'Noun'],
    ['Producers', 'Producteurs', 'Yapımcılar', 'Noun'], ['Culture', 'Culture', 'Kültür', 'Noun'], ['Fashion', 'Mode', 'Moda', 'Noun'],
    ['Trend', 'Tendance', 'Trend', 'Noun'], ['Inspiration', 'Inspiration', 'İlham', 'Noun']
  ]),
  ...createLevel(14, [
    ['Doctor', 'Docteur', 'Doktor', 'Noun'], ['Nurse', 'Infirmière', 'Hemşire', 'Noun'], ['Engineer', 'Ingénieur', 'Mühendis', 'Noun'],
    ['Lawyer', 'Avocat', 'Avukat', 'Noun'], ['Police', 'Police', 'Polis', 'Noun'], ['Firefighter', 'Pompier', 'İtfaiyeci', 'Noun'],
    ['Chef', 'Chef', 'Aşçı', 'Noun'], ['Waiter', 'Serveur', 'Garson', 'Noun'], ['Worker', 'Ouvrier', 'İşçi', 'Noun'],
    ['Pilot', 'Pilote', 'Pilot', 'Noun'], ['Farmer', 'Fermier', 'Çiftçi', 'Noun'], ['Scientist', 'Scientifique', 'Bilim insanı', 'Noun'],
    ['Dentist', 'Dentiste', 'Diş hekimi', 'Noun'], ['Driver', 'Chauffeur', 'Şoför', 'Noun'], ['Manager', 'Manager', 'Yönetici', 'Noun'],
    ['Accountant', 'Comptable', 'Muhasebeci', 'Noun'], ['Baker', 'Boulanger', 'Fırıncı', 'Noun'], ['Butcher', 'Boucher', 'Kasap', 'Noun'],
    ['Carpenter', 'Charpentier', 'Marangoz', 'Noun'], ['Electrician', 'Électricien', 'Elektrikçi', 'Noun'], ['Plumber', 'Plombier', 'Tesisatçı', 'Noun'],
    ['Tailor', 'Tailleur', 'Terzi', 'Noun'], ['Hairdresser', 'Coiffeur', 'Kuaför', 'Noun'], ['Guard', 'Garde', 'Bekçi', 'Noun'],
    ['Judge', 'Juge', 'Hakim', 'Noun'], ['Watch', 'Montre', 'Saat', 'Noun'], ['Ring', 'Bague', 'Yüzük', 'Noun'],
    ['Necklace', 'Collier', 'Kolye', 'Noun'], ['Earrings', 'Boucles d\'oreilles', 'Küpeler', 'Noun'], ['Bracelet', 'Bracelet', 'Bilezik', 'Noun'],
    ['Glasses', 'Lunettes', 'Gözlük', 'Noun'], ['Hat', 'Chapeau', 'Şapka', 'Noun'], ['Cap', 'Casquette', 'Kep', 'Noun'],
    ['Belt', 'Ceinture', 'Kemer', 'Noun'], ['Wallet', 'Portefeuille', 'Cüzdan', 'Noun'], ['Purse', 'Sac à main', 'El çantası', 'Noun'],
    ['Scarf', 'Écharpe', 'Atkı', 'Noun'], ['Gloves', 'Gants', 'Eldiven', 'Noun'], ['Tie', 'Cravate', 'Kravat', 'Noun'],
    ['Umbrella', 'Parapluie', 'Şemsiye', 'Noun'], ['Jewelry', 'Bijoux', 'Mücevher', 'Noun'], ['Silver', 'Argent', 'Gümüş', 'Noun'],
    ['Gold', 'Or', 'Altın', 'Noun'], ['Diamond', 'Diamant', 'Elmas', 'Noun'], ['Suitcase', 'Valise', 'Valiz', 'Noun'],
    ['Bag', 'Sac', 'Çanta', 'Noun'], ['Keyring', 'Porte-clés', 'Anahtarlık', 'Noun'], ['Button', 'Bouton', 'Düğme', 'Noun'],
    ['Pocket', 'Poche', 'Cep', 'Noun'], ['Zip', 'Fermeture éclair', 'Fermuar', 'Noun']
  ]),

  // SEVİYE 15-16: VÜCUT, AİLE & DOĞA (50 each)
  ...createLevel(15, [
    ['Head', 'Tête', 'Baş', 'Noun'], ['Eye', 'Œil', 'Göz', 'Noun'], ['Ear', 'Oreille', 'Kulak', 'Noun'],
    ['Nose', 'Nez', 'Burun', 'Noun'], ['Mouth', 'Bouche', 'Ağız', 'Noun'], ['Hair', 'Cheveux', 'Saç', 'Noun'],
    ['Neck', 'Cou', 'Boyun', 'Noun'], ['Shoulder', 'Épaule', 'Omuz', 'Noun'], ['Arm', 'Bras', 'Kol', 'Noun'],
    ['Hand', 'Main', 'El', 'Noun'], ['Finger', 'Doigt', 'Parmak', 'Noun'], ['Leg', 'Jambe', 'Bacak', 'Noun'],
    ['Foot', 'Pied', 'Ayak', 'Noun'], ['Knee', 'Genou', 'Diz', 'Noun'], ['Heart', 'Cœur', 'Kalp', 'Noun'],
    ['Brain', 'Cerveau', 'Beyin', 'Noun'], ['Blood', 'Sang', 'Kan', 'Noun'], ['Skin', 'Peau', 'Deri', 'Noun'],
    ['Face', 'Visage', 'Yüz', 'Noun'], ['Back', 'Dos', 'Sırt', 'Noun'], ['Body', 'Corps', 'Vücut', 'Noun'],
    ['Bone', 'Os', 'Kemik', 'Noun'], ['Muscle', 'Muscle', 'Kas', 'Noun'], ['Tooth', 'Dent', 'Diş', 'Noun'],
    ['Tongue', 'Langue', 'Dil', 'Noun'], ['Lip', 'Lèvre', 'Dudak', 'Noun'], ['Eyebrow', 'Sourcil', 'Kaş', 'Noun'],
    ['Eyelash', 'Cil', 'Kirpik', 'Noun'], ['Forehead', 'Front', 'Alın', 'Noun'], ['Chin', 'Menton', 'Çene', 'Noun'],
    ['Cheek', 'Joue', 'Yanak', 'Noun'], ['Throat', 'Gorge', 'Boğaz', 'Noun'], ['Chest', 'Poitrine', 'Göğüs', 'Noun'],
    ['Stomach', 'Estomac', 'Mide', 'Noun'], ['Waist', 'Taille', 'Bel', 'Noun'], ['Hip', 'Hanche', 'Kalça', 'Noun'],
    ['Elbow', 'Coude', 'Dirsek', 'Noun'], ['Wrist', 'Poignet', 'Bilek', 'Noun'], ['Thumb', 'Pouce', 'Baş parmak', 'Noun'],
    ['Nail', 'Ongle', 'Tırnak', 'Noun'], ['Ankle', 'Cheville', 'Ayak bileği', 'Noun'], ['Heel', 'Talon', 'Topuk', 'Noun'],
    ['Toe', 'Orteil', 'Ayak parmağı', 'Noun'], ['Lung', 'Poumon', 'Akciğer', 'Noun'], ['Liver', 'Foie', 'Karaciğer', 'Noun'],
    ['Kidney', 'Rein', 'Böbrek', 'Noun'], ['Skeleton', 'Squelette', 'İskelet', 'Noun'], ['Organ', 'Organe', 'Organ', 'Noun'],
    ['Breath', 'Souffle', 'Nefes', 'Noun'], ['Pulse', 'Pouls', 'Nabız', 'Noun']
  ]),
  ...createLevel(16, [
    ['Family', 'Famille', 'Aile', 'Noun'], ['Mother', 'Mère', 'Anne', 'Noun'], ['Father', 'Père', 'Baba', 'Noun'],
    ['Sister', 'Sœur', 'Kız Kardeş', 'Noun'], ['Brother', 'Frère', 'Erkek Kardeş', 'Noun'], ['Baby', 'Bébé', 'Bebek', 'Noun'],
    ['Child', 'Enfant', 'Çocuk', 'Noun'], ['Grandmother', 'Grand-mère', 'Büyükanne', 'Noun'], ['Grandfather', 'Grand-père', 'Büyükbaba', 'Noun'],
    ['Aunt', 'Tante', 'Teyze/Hala', 'Noun'], ['Uncle', 'Oncle', 'Amca/Dayı', 'Noun'], ['Cousin', 'Cousin', 'Kuzen', 'Noun'],
    ['Parents', 'Parents', 'Ebeveyn', 'Noun'], ['Friend', 'Ami', 'Arkadaş', 'Noun'], ['Nature', 'Nature', 'Doğa', 'Noun'],
    ['Tree', 'Arbre', 'Ağaç', 'Noun'], ['Flower', 'Fleur', 'Çiçek', 'Noun'], ['Grass', 'Herbe', 'Çim', 'Noun'],
    ['River', 'Rivière', 'Nehir', 'Noun'], ['Mountain', 'Montagne', 'Dağ', 'Noun'], ['Sun', 'Soleil', 'Güneş', 'Noun'],
    ['Moon', 'Lune', 'Ay', 'Noun'], ['Sky', 'Ciel', 'Gökyüzü', 'Noun'], ['Cloud', 'Nuage', 'Bulut', 'Noun'],
    ['Rain', 'Pluie', 'Yağmur', 'Noun'], ['Snow', 'Neige', 'Kar', 'Noun'], ['Wind', 'Vent', 'Rüzgar', 'Noun'],
    ['Storm', 'Tempête', 'Fırtına', 'Noun'], ['Lightning', 'Éclair', 'Şimşek', 'Noun'], ['Bird', 'Oiseau', 'Kuş', 'Noun'],
    ['Cat', 'Chat', 'Kedi', 'Noun'], ['Dog', 'Chien', 'Köpek', 'Noun'], ['Horse', 'Cheval', 'At', 'Noun'],
    ['Cow', 'Vache', 'İnek', 'Noun'], ['Sheep', 'Mouton', 'Koyun', 'Noun'], ['Goat', 'Chèvre', 'Keçi', 'Noun'],
    ['Rabbit', 'Lapin', 'Tavşan', 'Noun'], ['Duck', 'Canard', 'Ördek', 'Noun'], ['Chicken', 'Poulet', 'Tavuk', 'Noun'],
    ['Leaf', 'Feuille', 'Yaprak', 'Noun'], ['Branch', 'Branche', 'Dal', 'Noun'], ['Root', 'Racine', 'Kök', 'Noun'],
    ['Seed', 'Graine', 'Tohum', 'Noun'], ['Fruit', 'Fruit', 'Meyve', 'Noun'], ['Wood', 'Bois', 'Odun', 'Noun'],
    ['Dirt', 'Terre', 'Toprak', 'Noun'], ['Sand', 'Sable', 'Kum', 'Noun'], ['Stone', 'Pierre', 'Taş', 'Noun'],
    ['Lake', 'Lac', 'Göl', 'Noun'], ['Hill', 'Colline', 'Tepe', 'Noun']
  ]),

  // SEVİYE 17-18: UZAY, OKYANUS & ORMAN (50 each)
  ...createLevel(17, [
    ['Space', 'Espace', 'Uzay', 'Noun'], ['Star', 'Étoile', 'Yıldız', 'Noun'], ['Planet', 'Planète', 'Gezegen', 'Noun'],
    ['Galaxy', 'Galaxie', 'Galaksi', 'Noun'], ['Universe', 'Univers', 'Evren', 'Noun'], ['Rocket', 'Fusée', 'Roket', 'Noun'],
    ['Astronaut', 'Astronaute', 'Astronot', 'Noun'], ['Gravity', 'Gravité', 'Yerçekimi', 'Noun'], ['Orbit', 'Orbite', 'Yörünge', 'Noun'],
    ['Light', 'Lumière', 'Işık', 'Noun'], ['Void', 'Vide', 'Boşluk', 'Noun'], ['Atmosphere', 'Atmosphère', 'Atmosfer', 'Noun'],
    ['Earth', 'Terre', 'Dünya', 'Noun'], ['Mars', 'Mars', 'Mars', 'Noun'], ['Jupiter', 'Jupiter', 'Jüpiter', 'Noun'],
    ['Saturn', 'Saturne', 'Satürn', 'Noun'], ['Venus', 'Vénus', 'Venüs', 'Noun'], ['Mercury', 'Mercure', 'Merkür', 'Noun'],
    ['Uranus', 'Uranus', 'Uranüs', 'Noun'], ['Neptune', 'Neptune', 'Neptün', 'Noun'], ['Sun', 'Soleil', 'Güneş', 'Noun'],
    ['Moon', 'Lune', 'Ay', 'Noun'], ['Comet', 'Comète', 'Kuyruklu yıldız', 'Noun'], ['Asteroid', 'Astéroïde', 'Asteroid', 'Noun'],
    ['Meteor', 'Météore', 'Meteor', 'Noun'], ['Black hole', 'Trou noir', 'Kara delik', 'Noun'], ['Space station', 'Station spatiale', 'Uzay istasyonu', 'Noun'],
    ['Satellite', 'Satellite', 'Uydu', 'Noun'], ['Telescope', 'Télescope', 'Teleskop', 'Noun'], ['Alien', 'Extraterrestre', 'Uzaylı', 'Noun'],
    ['Discovery', 'Découverte', 'Keşif', 'Noun'], ['Journey', 'Voyage', 'Yolculuk', 'Noun'], ['Mission', 'Mission', 'Görev', 'Noun'],
    ['Spaceship', 'Vaisseau spatial', 'Uzay gemisi', 'Noun'], ['Solar system', 'Système solaire', 'Güneş sistemi', 'Noun'], ['Eclipse', 'Éclipse', 'Tutulma', 'Noun'],
    ['Constellation', 'Constellation', 'Takımyıldız', 'Noun'], ['Cosmos', 'Cosmos', 'Kozmos', 'Noun'], ['Supernova', 'Supernova', 'Süpernova', 'Noun'],
    ['Launch', 'Lancement', 'Fırlatma', 'Noun'], ['Alien', 'Alién', 'Yabancı', 'Noun'], ['Explorer', 'Explorateur', 'Kaşif', 'Noun'],
    ['Infinity', 'Infini', 'Sonsuzluk', 'Noun'], ['Future', 'Futur', 'Gelecek', 'Noun'], ['Time', 'Temps', 'Zaman', 'Noun'],
    ['Speed', 'Vitesse', 'Hız', 'Noun'], ['Vast', 'Vaste', 'Geniş', 'Adjective'], ['Cold', 'Froid', 'Soğuk', 'Adjective'],
    ['Dark', 'Sombre', 'Karanlık', 'Adjective'], ['Bright', 'Lumineux', 'Parlak', 'Adjective']
  ]),
  ...createLevel(18, [
    ['Ocean', 'Océan', 'Okyanus', 'Noun'], ['Sea', 'Mer', 'Deniz', 'Noun'], ['Wave', 'Vague', 'Dalga', 'Noun'],
    ['Fish', 'Poisson', 'Balık', 'Noun'], ['Shark', 'Requin', 'Köpekbalığı', 'Noun'], ['Whale', 'Baleine', 'Balina', 'Noun'],
    ['Dolphin', 'Dauphin', 'Yunus', 'Noun'], ['Octopus', 'Poulpe', 'Ahtapot', 'Noun'], ['Crab', 'Crabe', 'Yengeç', 'Noun'],
    ['Coral', 'Corail', 'Mercan', 'Noun'], ['Shell', 'Coquille', 'Kabuk', 'Noun'], ['Beach', 'Plage', 'Plaj', 'Noun'],
    ['Island', 'Île', 'Ada', 'Noun'], ['Ship', 'Navire', 'Gemi', 'Noun'], ['Boat', 'Bateau', 'Tekne', 'Noun'],
    ['Water', 'Eau', 'Su', 'Noun'], ['Deep', 'Profond', 'Derin', 'Adjective'], ['Blue', 'Bleu', 'Mavi', 'Adjective'],
    ['Forest', 'Forêt', 'Orman', 'Noun'], ['Tree', 'Arbre', 'Ağaç', 'Noun'], ['Leaf', 'Feuille', 'Yaprak', 'Noun'],
    ['Root', 'Racine', 'Kök', 'Noun'], ['Flower', 'Fleur', 'Çiçek', 'Noun'], ['Animal', 'Animal', 'Hayvan', 'Noun'],
    ['Bird', 'Oiseau', 'Kuş', 'Noun'], ['Bear', 'Ours', 'Ayı', 'Noun'], ['Wolf', 'Loup', 'Kurt', 'Noun'],
    ['Deer', 'Cerf', 'Geyik', 'Noun'], ['Fox', 'Renard', 'Tilki', 'Noun'], ['Squirrel', 'Écureuil', 'Sincap', 'Noun'],
    ['Lion', 'Lion', 'Aslan', 'Noun'], ['Tiger', 'Tigre', 'Kaplan', 'Noun'], ['Elephant', 'Éléphant', 'Fil', 'Noun'],
    ['Monkey', 'Singe', 'Maymun', 'Noun'], ['Snake', 'Serpent', 'Yılan', 'Noun'], ['Frog', 'Grenouille', 'Kurbağa', 'Noun'],
    ['Insect', 'Insecte', 'Böcek', 'Noun'], ['Butterfly', 'Papillon', 'Kelebek', 'Noun'], ['Nature', 'Nature', 'Doğa', 'Noun'],
    ['Green', 'Vert', 'Yeşil', 'Adjective'], ['Wild', 'Sauvage', 'Vahşi', 'Adjective'], ['Fresh', 'Frais', 'Taze', 'Adjective'],
    ['Quiet', 'Calme', 'Sessiz', 'Adjective'], ['Peaceful', 'Paisible', 'Huzurlu', 'Adjective'], ['Path', 'Chemin', 'Yol', 'Noun'],
    ['Cave', 'Grotte', 'Mağara', 'Noun'], ['Waterfall', 'Cascade', 'Şelale', 'Noun'], ['Lake', 'Lac', 'Göl', 'Noun'],
    ['Earth', 'Terre', 'Toprak', 'Noun'], ['Sky', 'Ciel', 'Gökyüzü', 'Noun']
  ]),

  // SEVİYE 19-20: SEYAHAT, ÜLKELER & DUYGULAR (50 each)
  ...createLevel(19, [
    ['Travel', 'Voyage', 'Seyahat', 'Noun'], ['Trip', 'Voyage', 'Gezi', 'Noun'], ['Hotel', 'Hôtel', 'Otel', 'Noun'],
    ['Map', 'Carte', 'Harita', 'Noun'], ['Guide', 'Guide', 'Rehber', 'Noun'], ['World', 'Monde', 'Dünya', 'Noun'],
    ['Country', 'Pays', 'Ülke', 'Noun'], ['City', 'Ville', 'Şehir', 'Noun'], ['Flag', 'Drapeau', 'Bayrak', 'Noun'],
    ['Holiday', 'Vacances', 'Tatil', 'Noun'], ['Culture', 'Culture', 'Kültür', 'Noun'], ['History', 'Histoire', 'Tarih', 'Noun'],
    ['Turkey', 'Turquie', 'Türkiye', 'Noun'], ['England', 'Angleterre', 'İngiltere', 'Noun'], ['France', 'France', 'Fransa', 'Noun'],
    ['Germany', 'Allemagne', 'Almanya', 'Noun'], ['Italy', 'Italie', 'İtalya', 'Noun'], ['Spain', 'Espagne', 'İspanya', 'Noun'],
    ['USA', 'États-Unis', 'ABD', 'Noun'], ['Japan', 'Japon', 'Japonya', 'Noun'], ['China', 'Chine', 'Çin', 'Noun'],
    ['Capital', 'Capitale', 'Başkent', 'Noun'], ['Border', 'Frontière', 'Sınır', 'Noun'], ['Visit', 'Visiter', 'Ziyaret etmek', 'Verb'],
    ['Explore', 'Explorer', 'Keşfetmek', 'Verb'], ['Tour', 'Tour', 'Tur', 'Noun'], ['Adventure', 'Aventure', 'Macera', 'Noun'],
    ['Stay', 'Rester', 'Kalmak', 'Verb'], ['Leave', 'Partir', 'Ayrılmak', 'Verb'], ['Stay', 'Rester', 'Kalmak', 'Verb'],
    ['Airport', 'Aéroport', 'Havalimanı', 'Noun'], ['Railway', 'Chemin de fer', 'Demiryolu', 'Noun'], ['Road', 'Route', 'Yol', 'Noun'],
    ['Mountain', 'Montagne', 'Dağ', 'Noun'], ['Sea', 'Mer', 'Deniz', 'Noun'], ['Lake', 'Lac', 'Göl', 'Noun'],
    ['Nature', 'Nature', 'Doğa', 'Noun'], ['Museum', 'Musée', 'Müze', 'Noun'], ['Palace', 'Palais', 'Saray', 'Noun'],
    ['Castle', 'Château', 'Kale', 'Noun'], ['Temple', 'Temple', 'Tapınak', 'Noun'], ['Food', 'Nourriture', 'Yemek', 'Noun'],
    ['Language', 'Langue', 'Dil', 'Noun'], ['Souvenir', 'Souvenir', 'Hediyelik eşya', 'Noun'], ['Camera', 'Appareil photo', 'Kamera', 'Noun'],
    ['Photo', 'Photo', 'Fotoğraf', 'Noun'], ['Famous', 'Célèbre', 'Ünlü', 'Adjective'], ['Local', 'Local', 'Yerel', 'Adjective'],
    ['Foreign', 'Étranger', 'Yabancı', 'Adjective'], ['Global', 'Global', 'Küresel', 'Adjective']
  ]),
  ...createLevel(20, [
    ['Happy', 'Heureux', 'Mutlu', 'Adjective'], ['Sad', 'Triste', 'Üzgün', 'Adjective'], ['Angry', 'Colère', 'Öfkeli', 'Adjective'],
    ['Fear', 'Peur', 'Korku', 'Noun'], ['Love', 'Amour', 'Aşk', 'Noun'], ['Peace', 'Paix', 'Barış', 'Noun'],
    ['Joy', 'Joie', 'Sevinç', 'Noun'], ['Surprise', 'Surprise', 'Sürpriz', 'Noun'], ['Brave', 'Brave', 'Cesur', 'Adjective'],
    ['Shy', 'Timide', 'Utangaç', 'Adjective'], ['Funny', 'Drôle', 'Komik', 'Adjective'], ['Serious', 'Sérieux', 'Ciddi', 'Adjective'],
    ['Smart', 'Intelligent', 'Zeki', 'Adjective'], ['Kind', 'Gentil', 'Nazik', 'Adjective'], ['Hope', 'Espoir', 'Umut', 'Noun'],
    ['Dream', 'Rêve', 'Rüya', 'Noun'], ['Feeling', 'Sentiment', 'Duygu', 'Noun'], ['Opinion', 'Opinion', 'Görüş', 'Noun'],
    ['Idea', 'Idée', 'Fikir', 'Noun'], ['Memory', 'Mémoire', 'Hafıza', 'Noun'], ['Truth', 'Vérité', 'Gerçek', 'Noun'],
    ['Success', 'Succès', 'Başarı', 'Noun'], ['Goal', 'But', 'Hedef', 'Noun'], ['Choice', 'Choix', 'Seçim', 'Noun'],
    ['Will', 'Volonté', 'İrade', 'Noun'], ['Care', 'Soin', 'Özen', 'Noun'], ['Help', 'Aide', 'Yardım', 'Noun'],
    ['Trust', 'Confiance', 'Güven', 'Noun'], ['Hate', 'Haine', 'Nefret', 'Noun'], ['Bored', 'Ennuyé', 'Sıkılmış', 'Adjective'],
    ['Tired', 'Fatigué', 'Yorgun', 'Adjective'], ['Excited', 'Excité', 'Heyecanlı', 'Adjective'], ['Proud', 'Fier', 'Gururlu', 'Adjective'],
    ['Calm', 'Calme', 'Sakin', 'Adjective'], ['Strong', 'Fort', 'Güçlü', 'Adjective'], ['Weak', 'Faible', 'Zayıf', 'Adjective'],
    ['Busy', 'Occupé', 'Meşgul', 'Adjective'], ['Lazy', 'Paresseux', 'Tembel', 'Adjective'], ['Honest', 'Honnête', 'Dürüst', 'Adjective'],
    ['Free', 'Libre', 'Özgür', 'Adjective'], ['Equal', 'Égal', 'Eşit', 'Adjective'], ['Safe', 'Sûr', 'Güvenli', 'Adjective'],
    ['Good', 'Bon', 'İyi', 'Adjective'], ['Bad', 'Mauvais', 'Kötü', 'Adjective'], ['Best', 'Meilleur', 'En iyi', 'Adjective'],
    ['Worst', 'Pire', 'En kötü', 'Adjective'], ['Beautiful', 'Beau', 'Güzel', 'Adjective'], ['Ugly', 'Laid', 'Çirkin', 'Adjective'],
    ['Young', 'Jeune', 'Genç', 'Adjective'], ['Old', 'Vieux', 'Yaşlı', 'Adjective']
  ])
];
